# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b1fbb82a8d2a8beb49b66372f4dbcffd7ff9d9b88e07edabdfff7e4d31b3e16e9595dbd8988e1d0ef4fcbc2d9068e6b8354781598c5297f93e03f25b2230b60

test:
  secret_key_base: ed01a265fa68c45674baa80c98a25c18ccdfc36966d00aaf3d369a3da7ccf0b73b80527c3bb8e87d835eb3f35041125e778e9781fe2e39e26361198ad4e49946

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
